#!/usr/bin/env bash


# store the location of the script
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"


# make Apps directory if it doesn't already exist
mkdir -p $HOME/Apps


# download archive
curl -sL https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux64&lang=en-US -o /tmp/firefox-dev.tar.gz


# extract to Apps directory
tar xzvf /tmp/firefox-dev.tar.gz -C $HOME/Apps


# install files
install -D $SCRIPT_DIR/config/firefox-dev.desktop -t $HOME/.local/share/applications



# update desktop files
sed -i "s|Icon=firefox-dev|Icon=$HOME/Apps/firefox/browser/chrome/icons/default/default128.png|g" $HOME/.local/share/applications/firefox-dev.desktop
sed -i "s|Exec=firefox-dev|Exec=$HOME/Apps/firefox/firefox|g" $HOME/.local/share/applications/firefox-dev.desktop


# copy configs



# cleanup
rm -f /tmp/firefox-dev.tar.gz
