#!/usr/bin/env bash


# store the location of the script
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"



# setup values




# make install directory if it doesn't already exist




# download archive
curl -sL https://github.com/dylanaraps/neofetch/releases/latest -o /tmp/neofetch.tar.gz



# extract to install directory
tar xzvf /tmp/neofetch.tar.gz -C /tmp/



# install files
install -D /tmp/neofetch/neofetch -t $HOME/.local/bin



# update desktop files




# copy configs




# cleanup
rm -rf /tmp/neofetch.tar.gz /tmp/neofetch
