#!/usr/bin/env bash

# pre script checks





# store the location of the script
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"




# setup values





# make directories if they don't already exist
mkdir -p /tmp/installers
mkdir -p $HOME/.local/bin



# download archive
curl -sL https://github.com/dylanaraps/neofetch/releases/latest -o /tmp/installers/neofetch.tar.gz




# extract archive
tar xzvf /tmp/installers/neofetch.tar.gz -C /tmp/installers/




# install files
install -D /tmp/installers/neofetch/neofetch -t $HOME/.local/bin




# update desktop files





# copy configs





# cleanup
rm -rf /tmp/installers/neofetch.tar.gz /tmp/installers/neofetch
