#!/usr/bin/env bash


# store the location of the script
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"



# setup values




# make directories if they don't already exist
mkdir -p $HOME/Apps
mkdir -p $HOME/.config/Code/User


# download archive
curl -sL https://code.visualstudio.com/sha/download?build=stable&os=linux-x64 -o /tmp/code.tar.gz



# extract archive
tar xzvf /tmp/code.tar.gz -C $HOME/Apps



# install files
install -D $SCRIPT_DIR/config/code.desktop -t $HOME/.local/share/applications
ln -s $HOME/Apps/VSCode-linux-x64/bin/code $HOME/.local/bin/code


# update desktop files
sed -i "s|Icon=vscode|Icon=$HOME/Apps/VSCode-linux-x64/resources/app/resources/linux/code.png|g" $HOME/.local/share/applications/code.desktop
sed -i "s|Exec=/usr/share/code/code|Exec=$HOME/Apps/VSCode-linux-x64/code|g" $HOME/.local/share/applications/code.desktop


# copy configs
cp $SCRIPT_DIR/config/*.json $HOME/.config/Code/User



# cleanup
rm -f /tmp/code.tar.gz
