#!/usr/bin/env bash

# SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";
# echo $SCRIPT_DIR

# SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
# echo "Script directory: $SCRIPT_DIR"

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

ls -la $SCRIPT_DIR/config

if [ $# -eq 0 ]; then
  echo "No Parameters Passed!"
  exit 1
fi

PARAM=$1

echo "Parameter Passed: $PARAM"

