#!/usr/bin/env bash

# pre script checks





# store the location of the script
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"




# setup values





# make directories if they don't already exist





# download archive





# extract archive





# install files
install -D $SCRIPT_DIR/bin/prime-run -t $HOME/.local/bin




# update desktop files





# copy configs





# cleanup
