#!/usr/bin/env bash

# pre script checks





# store the location of the script
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"




# setup values





# make directories if they don't already exist
mkdir -p $HOME/.local/bin




# download archive





# extract archive





# install files
install -D $SCRIPT_DIR/bin/smb-mount -t $HOME/.local/bin
install -D $SCRIPT_DIR/bin/smb-umount -t $HOME/.local/bin



# update desktop files





# copy configs
cp $SCRIPT_DIR/config/.smb-credentials $HOME




# cleanup
