#!/usr/bin/env bash


# store the location of the script
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"



# setup values
fonts="JetBrainsMono Meslo"



# make directories if they don't already exist
for font in $fonts; do
    mkdir -p $HOME/.local/share/fonts/$font
done

# download archive
for font in $fonts; do
    curl -sL https://github.com/ryanoasis/nerd-fonts/releases/latest/download/$font.tar.xz -o /tmp/$font.tar.xz
done

# extract archive
for font in $fonts; do
    tar xf /tmp/$font.tar.xz -C $HOME/.local/share/fonts/$font/
done

# install files
fc-cache -fv



# update desktop files




# copy configs




# cleanup
for font in $fonts; do
    rm -f /tmp/$font.tar.xz
done
