#!/usr/bin/env bash


# store the location of the script
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"


# make Apps directory if it doesn't already exist
mkdir -p $HOME/Apps/lmms


# download archive
curl -sL https://github.com/LMMS/lmms/releases/download/v1.2.2/lmms-1.2.2-linux-x86_64.AppImage -o $HOME/Apps/lmms/lmms.AppImage


# extract to Apps directory



# install files
install -D $SCRIPT_DIR/config/lmms.desktop -t $HOME/.local/share/applications
install -D $SCRIPT_DIR/config/lmms-64x64.png -t $HOME/Apps/lmms


# update desktop files
sed -i "s|Icon=lmms|Icon=$HOME/Apps/lmms/lmms-64x64.png|g" $HOME/.local/share/applications/lmms.desktop
sed -i "s|Exec=lmms|Exec=env QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCALE_FACTOR=1 $HOME/Apps/lmms/lmms.AppImage|g" $HOME/.local/share/applications/lmms.desktop


# copy configs
