#!/usr/bin/env bash


# store the location of the script
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"



# setup values




# make install directory if it doesn't already exist
mkdir -p $HOME/Apps



# download archive
curl -sL https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.41.7-stable.tar.xz -o /tmp/flutter.tar.xz



# extract to install directory
tar xvf /tmp/flutter.tar.xz -C $HOME/Apps && mv $HOME/Apps/flutter* $HOME/Apps/flutter



# install files




# update desktop files




# copy configs




# cleanup
rm -f /tmp/flutter.tar.xz
