#!/usr/bin/env bash

# pre script checks





# store the location of the script
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"




# setup values





# make directories if they don't already exist
mkdir -p /tmp/installers
mkdir -p $HOME/Apps



# download archive
curl -sL https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.44.0-stable.tar.xz -o /tmp/installers/flutter.tar.xz




# extract archive
tar xvf /tmp/installers/flutter.tar.xz -C $HOME/Apps




# install files





# update desktop files





# copy configs





# cleanup
rm -f /tmp/installers/flutter.tar.xz
