#!/usr/bin/env bash


# store the location of the script
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"



# setup values




# make install directory if it doesn't already exist
mkdir -p $HOME/Apps



# download archive
curl -sL https://github.com/quarto-dev/quarto-cli/releases/download/v1.9.37/quarto-1.9.37-linux-amd64.tar.gz -o /tmp/quarto.tar.gz



# extract to install directory
tar xzvf /tmp/quarto.tar.gz -C $HOME/Apps && mv $HOME/Apps/quarto* $HOME/Apps/quarto



# install files
ln -s $HOME/Apps/quarto/bin/quarto $HOME/.local/bin/quarto



# update desktop files




# copy configs




# cleanup
rm -f /tmp/quarto.tar.gz
