#!/usr/bin/env bash

# pre script checks





# store the location of the script
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
VERSION=1.10.18



# setup values





# make directories if they don't already exist
mkdir -p /tmp/installers
mkdir -p $HOME/Apps



# download archive
curl -sL https://github.com/quarto-dev/quarto-cli/releases/download/v${VERSION}/quarto-${VERSION}-linux-amd64.tar.gz -o /tmp/installers/quarto.tar.gz




# extract archive
tar xzvf /tmp/installers/quarto.tar.gz -C $HOME/Apps




# install files
[ -L $HOME/.local/bin/quarto ] && rm $HOME/.local/bin/quarto
ln -s $HOME/Apps/quarto-${VERSION}/bin/quarto $HOME/.local/bin/quarto



# update desktop files





# copy configs





# cleanup
rm -f /tmp/installers/quarto.tar.gz
