#!/usr/bin/env bash


# store the location of the script
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"



# setup values




# make directories if they don't already exist
mkdir -p $HOME/Apps



# download archive
curl -sL https://github.com/quarto-dev/quarto-cli/releases/download/v1.9.37/quarto-1.9.37-linux-amd64.tar.gz -o /tmp/quarto.tar.gz



# extract archive
tar xzvf /tmp/quarto.tar.gz -C $HOME/Apps



# install files
[ -L $HOME/.local/bin/quarto ] && rm $HOME/.local/bin/quarto
ln -s $HOME/Apps/quarto-1.9.37/bin/quarto $HOME/.local/bin/quarto


# update desktop files




# copy configs




# cleanup
rm -f /tmp/quarto.tar.gz
