#!/usr/bin/env bash


# store the location of the script
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"



# setup values




# make directories if they don't already exist
mkdir -p $HOME/.local/bin



# download archive
curl -L https://github.com/kubernetes/kompose/releases/download/v1.38.0/kompose-linux-amd64 -o $HOME/.local/bin/kompose



# extract archive




# install files
chmod a+x $HOME/.local/bin/kompose



# update desktop files




# copy configs




# cleanup
