#!/usr/bin/env bash

# pre script checks





# store the location of the script
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"




# setup values





# make directories if they don't already exist
mkdir -p /tmp/installers
mkdir -p $HOME/Apps



# download archive
curl -sL https://files.multimc.org/downloads/mmc-develop-lin64.tar.gz -o /tmp/installers/MultiMC.tar.gz




# extract archive
tar xzvf /tmp/installers/MultiMC.tar.gz -C $HOME/Apps




# install files
install -D $SCRIPT_DIR/config/MultiMC.desktop -t $HOME/.local/share/applications
install -D $SCRIPT_DIR/config/MultiMC.svg -t $HOME/Apps/MultiMC



# update desktop files
sed -i "s|Icon=MultiMC|Icon=$HOME/Apps/MultiMC/MultiMC.svg|g" $HOME/.local/share/applications/MultiMC.desktop
sed -i "s|Exec=MultiMC|Exec=$HOME/Apps/MultiMC/MultiMC|g" $HOME/.local/share/applications/MultiMC.desktop



# copy configs





# cleanup
rm -f /tmp/installers/MultiMC.tar.gz
