#!/usr/bin/env bash

# pre script checks





# store the location of the script
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"




# setup values





# make directories if they don't already exist





# download archive
curl -sL https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm -o /tmp/msttcore-fonts-installer-2.6-1.noarch.rpm




# extract archive





# install files
dnf install /tmp/msttcore-fonts-installer-2.6-1.noarch.rpm




# update desktop files





# copy configs





# cleanup
rm -f /tmp/msttcore-fonts-installer-2.6-1.noarch.rpm
