#!/usr/bin/env bash

if [ $# -eq 0 ]; then
  echo "Please specify the local and remote paths to mount..."
  exit 1
fi

MOUNT_PATH=$1

mkdir -p ~/$MOUNT_PATH

sudo mount -t cifs //tristram.local/$2 ~/$MOUNT_PATH -o credentials=~/.smb-credentials,uid=1000,gid=1000
