#!/usr/bin/env bash

# pre script checks
if [ $# -eq 0 ]; then
  echo "Please specify 'user' or 'root'"
  exit 1
fi

# store the location of the script
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"




# setup values
USER=$1




# make directories if they don't already exist
mkdir -p $HOME/.local/bin




# download archive





# extract archive





# install files
cp $SCRIPT_DIR/bin/$USER/* -t $HOME/.local/bin




# update desktop files





# copy configs





# cleanup
