#!/usr/bin/env bash


dnf copr enable solopasha/hyprland

dnf install \
    hyprland \
    hyprland-devel \
    hypridle \
    hyprlock \
    hyprpaper \
    hyprnome \
    hyprpolkitagent \
    xdg-desktop-portal-hyprland \
    rofi \
    waybar \
    wlogout


# dnf remove hyprland hyprland-devel hypridle hyprlock hyprpaper hyprnome hyprpolkitagent xdg-desktop-portal-hyprland rofi waybar wlogout
