#!/bin/bash


# SDL
dnf install \
    SDL3 \
    SDL3-devel \
    SDL3_image \
    SDL3_image-devel \
    SDL3_sound \
    SDL3_sound-devel \
    SDL3_ttf \
    SDL3_ttf-devel


# Graphene
dnf install \
    graphene \
    graphene-devel


# GLFW
dnf install \
    glfw \
    glfw-devel


# GLAD
dnf install glad


# mesa libEGL
dnf install \
    mesa-libEGL \
    mesa-libEGL-devel


# mesa libGL
dnf install \
    mesa-libGL \
    mesa-libGL-devel


# libdecor
dnf install \
    libdecor \
    libdecor-devel


# freeglut (optional)
dnf install \
    freeglut \
    freeglut-devel


# EGL Wayland Support (optional)
dnf install \
    egl-wayland \
    egl-wayland-devel
