#!/bin/bash


# RPMFusion
dnf install \
    https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
    https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm


# FFMPEG
dnf swap ffmpeg-free ffmpeg --allowerasing


# Z Shell
dnf install zsh


# User Utils
dnf install figlet fortune-mod fastfetch


# System Utils
dnf install stow lshw btop htop


# Terminal Multiplexers
dnf install tmux screen


# Maintenance
dnf install rpmconf remove-retired-packages clean-rpm-gpg-pubkey symlinks dracut-config-rescue
