#!/bin/bash


# OBS
dnf install \
    obs-studio \
    obs-studio-plugin-vaapi \
    obs-studio-plugin-vkcapture \
    obs-studio-plugin-vlc-video \
    obs-studio-plugin-webkitgtk \
    obs-studio-plugin-x264
