#!/usr/bin/env bash


dnf config-manager addrepo --from-repofile=https://download.docker.com/linux/fedora/docker-ce.repo

dnf install \
    docker-ce \
    docker-ce-cli \
    containerd.io \
    docker-buildx-plugin \
    docker-compose-plugin
