#!/usr/bin/env bash


# store the location of the script
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"



# setup values




# make directories if they don't already exist
mkdir -p $HOME/.local/bin



# download archive
curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o $HOME/.local/bin/kubectl



# extract archive




# install files
chmod a+x $HOME/.local/bin/kubectl



# update desktop files




# copy configs




# cleanup
